### PR TITLE
UCD-115: limit access to local wayland sockets

### PR DESCRIPTION
**Pull request by sergio-costas**
To allow any program to get access to the Wayland socket in Ubuntu Core Desktop, no matter if it is running inside or outside a snap, a hard link is made from the real socket (located at /run/user/XXXX/snap.ubuntu-desktop-session/wayland-0) to the expected place (/run/user/XXXX/wayland-0).

Unfortunately, due to the way AppArmor works, it is able to detect that, although a snapped program is accessing the global path, it really is trying to access the socket in the local path, something that, by default, is forbidden.

Currently this is solved with this AppArmor rule:

    owner /run/user/[0-9]*/{,*/}wayland-[0-9]* rw,

This rule has the problem that it allows any snap to access any wayland-X file/socket located inside the private XDG folder of any other snap, which is a security breach (for example, it allows two apparently unrelated snaps to communicate between them without any kind of control).

The solution presented in this patch consists on allowing to access only to the socket placed in the folder of the snap that is implementing the wayland slot.

Thanks for helping us make a better snapd!
Have you signed the [license agreement](https://www.ubuntu.com/legal/contributors) and read the [contribution guide](https://github.com/snapcore/snapd/blob/master/CONTRIBUTING.md)?

### CODE REVIEW

**Comment by sergio-costas** [comment]
I think that this PR will be required when trying to merge these changes to the upstream snapd. @jhenstridge If you approve this, I'll prepare a patch for upstream with them too.

**Comment by sergio-costas** [comment]
BTW: here I'm using `if !release.OnClassic` to decide whether to add or not the access to the "internal" wayland socket, but in the audio patch I used `if slot.Snap().SnapName() != "snapd"`. Which one do you think is the best method? (to unify code...)

**Comment by jhenstridge** [comment]
I've got an upstream PR related to this here: https://github.com/snapcore/snapd/pull/12069. The `wayland.go` changes are mostly the same as yours, but I had trouble getting the tests passing correctly on the kernels in some of the older releases (where the AppArmor rules did not seem to match the socket for whatever reason).

**Comment by kenvandine** [comment]
@sergio-costas is this still needed?  If so, can  you please resolve the conflicts?

**Comment by sergio-costas** [comment]
@kenvandine Based on what's left after rebasing, I would say that no, it's not needed anymore. Closing.

**Pull request closed without merging**
