### PR TITLE
interfaces/desktop: allow access to GDM for lock screen support

### PR DESCRIPTION
**Pull request by kenvandine**
Thanks for helping us make a better snapd!
Have you signed the [license agreement](https://www.ubuntu.com/legal/contributors) and read the [contribution guide](https://github.com/snapcore/snapd/blob/master/CONTRIBUTING.md)?

### CODE REVIEW

**Comment by kenvandine** [comment]
@jhenstridge this doesn't fix screen lock but it does prevent the gnome-shell notification at login that screen lock is unavailable.  I doubt desktop is the right interface here though, got any better suggestions?

**Comment by jhenstridge** [comment]
I think the desktop slot is a reasonable place to put this. It's something a snap would need to "be a desktop".

So, this is  the full interface that method comes from:

https://gitlab.gnome.org/GNOME/gdm/-/blob/main/daemon/gdm-manager.xml

From the look of it, most of the methods get called by the `gdm-wayland-session` and `gdm-x-session` helpers used to launch sessions. That runs from outside confinement though, so doesn't really matter. The call that's triggering the denial is in gnome-shell:

https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/main/js/misc/loginManager.js#L56-72

Above that, it looks like it uses D-Bus property access to decide whether it can lock the screen, so we probably want to allow that too.

Looking over more of the gnome-shell and gnome-session code, I don't see any other direct communication with GDM: just logind, which I think should be handled already by `login-session-observe` / `login-session-control`. So I wonder if it is just checking whether GDM is new enough to track the session state change via logind.

So hopefully you change + property access would be enough to get things working.

**Comment by jhenstridge** [comment]
The good news is that this is enough to let gnome-shell lock the screen. The bad news is that I can't enter my password to unlock the screen.

It looks like there is an `OpenReauthenticationChannel` D-Bus call that's being blocked. It looks like this involves communication over a private D-Bus connections. And it looks like GDM just dumps these sockets in `/tmp`, which is going to be a problem with the way snaps use a private /tmp.

**Comment by jhenstridge** [comment]
So we might be able to get this working with our current Gnome. When I run the blocked method from outside the sandbox, it's an abstract namespace socket:

```
$ busctl call --system org.gnome.DisplayManager /org/gnome/DisplayManager/Manager \
>     org.gnome.DisplayManager.Manager OpenReauthenticationChannel s james
s "unix:abstract=/tmp/dbus-FBsdk5qi"
```

As it's an abstract socket, we'd be able to grant access.

Unfortunately, on newer Ubuntu versions it returns a bus address like `"unix:path=/tmp/dbus-ulUnhV7w"`, which would be inaccessible.

Maybe the best option for future releases is to change where GDM puts these sockets (e.g. somewhere under `/run/gdm3`?).

**Comment by jhenstridge** [comment]
I think this should give us a working lockscreen now.

It's going to break as soon as we upgrade to glib >= 2.75.x though, as it changes what sort of socket GDBusServer creates. We'd basically be looking at https://bugs.launchpad.net/ubuntu/+source/ibus/+bug/2008279 but with no quick fix on the snapd side. It'll be a "patch GDM, and hope upstream accepts the change so we don't have to maintain the patch forever" change.

**Review by sergio-costas — APPROVED** [review]
Tested the changes, and they do work in Qemu.

**Pull request merged**
