### PR TITLE
o/restart: Don't automatically restart on a core desktop system

### PR DESCRIPTION
**Pull request by robert-ancell**
Make core desktop behave like a classic system and don't automatically do reboots.

### CODE REVIEW

**Comment by sergio-costas** [comment]
Mmm... this is a good temporary solution while we have a different snapd, but we should begin thinking how to define when a system is a core-desktop... Maybe add an specific interface for the desktop snap, and if there is a snap connected to it, consider the system a core-desktop instead of a core?

**Comment by kenvandine** [comment]
Is there a way to set ReleaseInfo.ID to ubuntu-core-desktop?  Ideally something we could set in our model, that could be easily set by other distros based on core desktop.

**Comment by sergio-costas** [comment]
@kenvandine The only thing that occurs to me is to modify `core-base-desktop`

**Comment by kenvandine** [comment]
> @kenvandine The only thing that occurs to me is to modify `core-base-desktop`

It would be nice to be able to do that outside of the common base for core-desktop, so flavors and other derivatives could be distinct.  But of course if that's the case, we couldn't use that to determine if we should restart.  I guess we could specify ubuntu-core-desktop as ID in core-base-desktop and allow flavors to override NAME, PRETTY_NAME, and VERSION via some other mechanism, but I guess there isn't a mechanism for that in core yet.

**Comment by robert-ancell** [comment]
I was also wondering if core-desktop should be considered different to core. Or is it like a classic desktop where you can install server, and add graphical packages or install desktop and remove graphical packages to convert between?

**Comment by robert-ancell** [comment]
My preferred architecture is snap will prompt if there is a prompting service running (e.g. snapd-desktop-integration) and otherwise will not. In that way you don't need to know if this is a "desktop" or not. Ultimately this will be a decision by the snapd team.

**Comment by robert-ancell** [comment]
I dropped the OnCoreDesktop flag and changed it to having a comment as to why we're changing this behaviour for now. We will discuss with the snapd team about if and how a flag should be done for Core Desktop.

**Comment by sergio-costas** [comment]
> My preferred architecture is snap will prompt if there is a prompting service running (e.g. snapd-desktop-integration) and otherwise will not. In that way you don't need to know if this is a "desktop" or not. Ultimately this will be a decision by the snapd team.

The problem that I can see here is that snapd-desktop-integration only runs while inside a gnome session. That means that a possible KDE version must have a Qt version (or the current Gtk version, which I don't think will be something that KDE users will like ;-) ) running to ensure that it does work. Also, it means that it can still reboot while in the GDM screen (and it can be very odd if you are going to enter and, suddendly, it reboots ;-) )

**Comment by robert-ancell** [comment]
> > My preferred architecture is snap will prompt if there is a prompting service running (e.g. snapd-desktop-integration) and otherwise will not. In that way you don't need to know if this is a "desktop" or not. Ultimately this will be a decision by the snapd team.
> 
> The problem that I can see here is that snapd-desktop-integration only runs while inside a gnome session. That means that a possible KDE version must have a Qt version (or the current Gtk version, which I don't think will be something that KDE users will like ;-) ) running to ensure that it does work. Also, it means that it can still reboot while in the GDM screen (and it can be very odd if you are going to enter and, suddendly, it reboots ;-) )

GDM is a session in itself and could run a prompt if desired. I guess it depends if we consider being on a login screen to be idle and suitable for doing updates in.

**Comment by sergio-costas** [comment]
@robert-ancell I suspect that we don't understand the same for "session" :-D

Also, AFAIK, GDM currently doesn't run snapped, but outside, so it won't be running snapd-desktop-integration.

**Comment by kenvandine** [comment]
@jhenstridge any feedback on this?

**Review by jhenstridge — APPROVED** [review]
This looks good, but I think you should add back the `release.OnCoreDesktop` bit from the previous version of the patch: even if it is hard coded to true in our branch for now, it makes it clearer where we want different behaviour.

And it's closer to something we could upstream (once we have `release.OnCoreDesktop` do a proper check.

**Review by kenvandine — APPROVED** [review]
LGTM

**Pull request merged**
